[world]
seed = "darkshuffle6"
name = "Dark Shuffle"
description = "Enter the darkness"
website = "https://darkshuffle.io/"

[world.socials]
x = "https://x.com/await_0x"
github = "https://github.com/Await-0x/dark-shuffle"

[namespace]
default = "darkshuffle_s0"

[writers]
"darkshuffle_s0" = [
    "darkshuffle_s0-game_systems",
    "darkshuffle_s0-battle_systems",
    "darkshuffle_s0-season_systems",
    "darkshuffle_s0-draft_systems",
    "darkshuffle_s0-map_systems",
    "darkshuffle_s0-config_systems",
]

[env]
# world_address = "0x0581f5394a8d43cebd38eda3d8e4e4f9bfb566c04485ba28cb47393bb0a82fe4"