[indexing]
world_block = 1014817
contracts = [
    "erc721:0x033faad68bac7f856a01eeb4f80f6e98e2cfca9dfc0c8774aee42d68406510cd"
]

[events]
raw = true
historical = ["darkshuffle_s0-TrophyCreation", "darkshuffle_s0-TrophyProgression"]
